#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres

#jwt.issuer.generator=UsochimochaBackend
#jwt.secret.password=932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00
#spring.jpa.hibernate.ddl-auto=create-drop