spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d41s29be5dus73coe0o0-a.oregon-postgres.render.com/usochicamochadb_havu?sslmode=require}
spring.datasource.username=${DB_USERNAME:gavo}
spring.datasource.password=${DB_PASSWORD:tJ1zCwbvOflH34yRxJKQuGZxW8I8FozY}

jwt.issuer.generator=${JWT_ISSUER:UsochimochaBackend}
jwt.secret.password=${JWT_SECRET:932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SHOW_SQL:false}
