spring.datasource.url=jdbc:postgresql://dpg-d280k495pdvs7382a6n0-a.virginia-postgres.render.com:5432/usochimochadb?sslmode=require
spring.datasource.username=barrantes
spring.datasource.password=HOEUaDMvv0TVsEpWvwmCxHbyAznKAI78

jwt.issuer.generator=UsochimochaBackend
jwt.secret.password=CAMBIA_ESTE_SECRET_FUERTE