spring.datasource.url=jdbc:postgresql://dpg-d280k495pdvs7382a6n0-a.virginia-postgres.render.com:5432/usochimochadb?sslmode=require
spring.datasource.username=barrantes
spring.datasource.password=HOEUaDMvv0TVsEpWvwmCxHbyAznKAI78

jwt.issuer.generator=UsochimochaBackend
jwt.secret.password=932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00

spring.jpa.hibernate.ddl-auto=update