spring.datasource.url=jdbc:postgresql://localhost:5432/cosasusochicamocha
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.issuer.generator=${JWT_ISSUER:UsochimochaBackend}
jwt.secret.password=${JWT_SECRET:932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SHOW_SQL:true}
