# Perfil para la base de datos SQL Server local (APP_usuchicamocha3)
# Uso: spring.profiles.active=sqlserver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=APP_usuchicamocha3;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

jwt.issuer.generator=UsochimochaBackend
jwt.secret.password=932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00
