spring.datasource.url=jdbc:postgresql://localhost:5432/APP_usuchicamocha3
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.issuer.generator=UsochimochaBackend
jwt.secret.password=932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00
