spring.application.name=UsochicamochaBackend
spring.profiles.active=dev

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

# Raíz de almacenamiento (ruta absoluta o relativa al directorio de trabajo del proceso)
app.storage.uploads-root=uploads