spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d2s46f7fte5s739iic90-a.virginia-postgres.render.com/usochicamochadb?sslmode=require}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:dl2ViygnjAv81lZBz4j1hPmsDe7g1EUF}

jwt.issuer.generator=${JWT_ISSUER:UsochimochaBackend}
jwt.secret.password=${JWT_SECRET:932aea0e6a85a4e55ac59d87f70aa47ec05b25709ad2ec95854771209849eb00}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
